[project]
name = "paydown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kanhaiya", email = "kanhaiyahss22110@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "openai>=3.24.0",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "radon>=6.0.1",
    "tavily-python>=0.8.4",
    "tree-sitter>=0.26.0",
    "tree-sitter-python>=0.25.0",
]

[project.scripts]
paydown = "paydown:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
